# Generated by Django 3.2.9 on 2022-02-05 17:41

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Категория предмета',
                'verbose_name_plural': 'Категории предметов',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('local_img', models.ImageField(default='media/img_default.jpg', upload_to='media/locations')),
                ('url', models.SlugField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('monster_img', models.FileField(default='media/img_default.jpg', upload_to=items.models.monster_directory_path)),
                ('url', models.SlugField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('locatinons', models.ManyToManyField(to='items.Location')),
            ],
            options={
                'verbose_name': 'Монстр',
                'verbose_name_plural': 'Монстры',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Предмет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.SlugField(max_length=250, unique=True)),
                ('item_img', models.ImageField(default='media/img_default.jpg', upload_to='media/items/')),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='Категория')),
                ('monster', models.ManyToManyField(related_name='monster_item', to='items.Monster', verbose_name='Монстр')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
