# Generated by Django 3.2.9 on 2022-02-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория предмета',
                'verbose_name_plural': 'Категории предметов',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('local_img', models.ImageField(default='media/img_default.jpg', upload_to='media/locations', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('monster_img', models.FileField(default='media/img_default.jpg', upload_to='media/monsters', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('locations', models.ManyToManyField(related_name='monsters_in_location', to='items.Location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Монстр',
                'verbose_name_plural': 'Монстры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.monster', verbose_name='Монстр')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Предмет: ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес:')),
                ('url', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('item_img', models.ImageField(default='media/img_default.jpg', upload_to='media/items/', verbose_name='Изображение')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='Категория')),
                ('monster', models.ManyToManyField(related_name='monster_item', to='items.Monster', verbose_name='Выпадает с: ')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
