# Generated by Django 3.2.9 on 2022-02-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='locatinons',
            new_name='locations',
        ),
    ]
