# Generated by Django 3.2.9 on 2022-03-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='url',
            new_name='slug',
        ),
    ]
