# Generated by Django 3.2.9 on 2022-02-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220209_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Итем'),
        ),
    ]
