# Generated by Django 3.2.9 on 2022-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_locatinons_monster_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='locations',
            field=models.ManyToManyField(related_name='monsters_in_location', to='items.Location'),
        ),
    ]
