# Generated by Django 3.2.9 on 2022-02-03 13:15

from django.db import migrations, models
import items.utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/items/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='local_img',
            field=models.ImageField(upload_to=items.utils.uploading.upload_function),
        ),
        migrations.AlterField(
            model_name='monster',
            name='locatinons',
            field=models.ManyToManyField(to='items.Location'),
        ),
    ]
