# Generated by Django 3.2.9 on 2022-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20220203_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='media/img_default.jpg', upload_to='media/items/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='local_img',
            field=models.ImageField(default='media/img_default.jpg', upload_to='media/locations'),
        ),
    ]
