# Generated by Django 3.2.9 on 2022-02-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_monster_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
