# Generated by Django 3.2.9 on 2022-02-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_comments_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='status',
        ),
    ]
